name: Release Supabase Migration (Production)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: Production
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      # Add these debug steps
      - name: Debug
        run: |
          echo "Project ID length: ${#SUPABASE_PROJECT_ID}"
          echo "DB Password length: ${#SUPABASE_DB_PASSWORD}"
          echo "Access Token length: ${#SUPABASE_ACCESS_TOKEN}"
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Link Supabase
        run: supabase link --project-ref $SUPABASE_PROJECT_ID
        working-directory: ./apps/api/supabase
      - name: Push Supabase
        run: supabase db push
        working-directory: ./apps/api/supabase
  apply:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      TF_VAR_linked_project: ${{ secrets.SUPABASE_PROJECT_ID }}
    defaults:
      run:
        working-directory: supabase/remotes

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - run: terraform init
      - run: terraform apply -auto-approve -no-color
